#!/bin/bash
export DISPLAY=:0
URL="about:blank"
TOR=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --url) URL="$2"; shift 2;;
        --tor) TOR=true; shift;;
        *) URL="$1"; shift;;
    esac
done

if [ "$TOR" = true ]; then
    systemctl start tor 2>/dev/null
    mkdir -p /home/mbuser/.mozilla/firefox/tor-profile
    firefox --class="MBBrowser-Tor" --profile /home/mbuser/.mozilla/firefox/tor-profile -no-remote --new-instance "$URL" &
else
    firefox "$URL" &
fi
