---
efiBootLoader: "grub"
kernel: "/vmlinuz"
img: "/initrd.img"
kernelLine: "/vmlinuz"
fallbackKernelLine: "/vmlinuz"
timeout: 5
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootloaderId: "MB-OS"

# KRITISCH für Acer: Installiere auch nach EFI/BOOT/BOOTX64.EFI
installEFIFallback: true
