---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: "EFI"
defaultPartitionTableType: gpt
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs"]
